/*
 * mos_audio.h — ES8311 audio codec driver for Agon MOS
 *
 * Hardware (Olimex ESP32-P4-PC Rev B):
 *   I2C0  SDA=GPIO7  SCL=GPIO8  (400 kHz)
 *   ES8311 I2C address: 0x18 (CE/AD0=GND)
 *   GPIO6 = CODEC_PWR_DIS# (active LOW — drive LOW to power on codec)
 *
 *   I2S0:
 *     DOUT (ESP→codec DAC): GPIO9  (I2S_DSDIN)
 *     WS   (LRCK):          GPIO10 (I2S_LRCK)
 *     DIN  (codec ADC→ESP): GPIO11 (I2S_ASDOUT)
 *     BCLK:                 GPIO12 (I2S_SCLK)
 *     MCLK:                 GPIO13 (I2S_MCLK)
 *
 * Audio format: 16384 Hz, mono, 16-bit signed PCM
 * MCLK = 256 × 16384 = 4,194,304 Hz  (generated by I2S APLL)
 * ESP32-P4 is I2S master; ES8311 is slave.
 *
 * API:
 *   mos_audio_init()        — initialize I2C + ES8311 + I2S
 *   mos_audio_write()       — write PCM samples (mono 16-bit)
 *   mos_audio_set_volume()  — set output volume 0-100
 *   mos_audio_deinit()      — release resources
 */

#pragma once

#include <stdint.h>
#include <stddef.h>
#include "esp_err.h"
#include "driver/i2s_std.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize the ES8311 codec and I2S interface.
 *
 * Powers on the codec (GPIO6 active LOW), initializes I2C0, configures
 * the ES8311 for 16384 Hz mono 16-bit output, and starts I2S0 with APLL.
 *
 * @return ESP_OK on success, or an esp_err_t on failure.
 */
esp_err_t mos_audio_init(void);

/**
 * @brief Write PCM audio samples to the DAC output.
 *
 * Sends mono 16-bit signed PCM samples to the ES8311 DAC via I2S DMA.
 * The I2S slot mode is MONO — samples are sent on the left channel only.
 *
 * @param  samples     Pointer to int16_t sample buffer
 * @param  num_samples Number of samples (not bytes) to write
 * @param  timeout_ms  Timeout in milliseconds (portMAX_DELAY = wait forever)
 * @return Number of samples actually written, or -1 on error.
 */
int mos_audio_write(const int16_t *samples, size_t num_samples, uint32_t timeout_ms);

/**
 * @brief Set the ES8311 DAC output volume.
 *
 * @param  volume  Volume level 0 (mute) to 100 (maximum)
 * @return ESP_OK on success.
 */
esp_err_t mos_audio_set_volume(int volume);

/**
 * @brief Get the I2S TX channel handle (for advanced use).
 *
 * @return I2S TX channel handle, or NULL if not initialized.
 */
i2s_chan_handle_t mos_audio_get_tx_handle(void);

/**
 * @brief De-initialize and release all audio resources.
 */
void mos_audio_deinit(void);

#ifdef __cplusplus
}
#endif
